from __future__ import annotations

from typing import Protocol

from .models import PairResult, Service, Transport


class Backend(Protocol):
    """Replace this adapter for tests or an alternative Android transport implementation."""

    def transports(self) -> list[Transport]: ...
    def inspect(self, address: str) -> Transport: ...
    def connect(self, endpoint: str) -> None: ...
    def pair(self, endpoint: str, code: str) -> PairResult: ...
    def disconnect(self, endpoint: str) -> None: ...
    def reconnect(self, address: str) -> None: ...
    def services(self) -> list[Service]: ...
    def diagnostics(self) -> dict[str, str]: ...


class Discovery(Protocol):
    def discover(self, seconds: float) -> tuple[list[Service], list[str]]: ...
